### ISSUE TITLE
Rearmar el template

### ISSUE THREAD

**Issue by LeandroCDN** [LeandroCDN/rent-protocol-front#1]
El GitHub es recortado de otro proyecto propio, pero tiene el navbar básico para navegar entre Pages. 
A realizar antes de trabajar con ramas
 - Cambiar los nombres de las Pages por : HOME - REGISTRO - ALQUILAR - VER - RESOLUCION DE CONFLICTOS
 En caso de que no exista una page, ver como se implementaron las otras y agregarlas

**Comment by ArielQuiroga** [comment]
Se completo el Issue
